name: Scrape Kings League Website

on:
  #Button in GitHub Action
  workflow_dispatch:

  # Do it by a URL
  repository_dispatch:
    types:
      - webhook

  # CronJob every hour on sunday
  schedule:
    - cron: "0 */1 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          node scraping/leaderboard.js
          git config user.name kings-league-bot
          git add -A
          git commit -m "[Bot] Update Kings League Database"
          git push origin main
